### ISSUE TITLE
Complete Example (spinnaker)

### ISSUE THREAD

**Issue by gboie** [Young-ook/terraform-aws-spinnaker#106]
First of all, great work! 
I am trying to run the complete example under the spinnaker (terraform-aws-spinnaker/examples/spinnaker/main.tf
) and I am getting the following error when I run terraform plan:

Error: Unsupported argument

  on main.tf line 53, in module "spinnaker":
  53:   aurora_instances = {

An argument named "aurora_instances" is not expected here.

Error: Unsupported argument

  on main.tf line 59, in module "spinnaker":
  59:   helm = {

An argument named "helm" is not expected here.

Thank you!

**Comment by Young-ook** [comment]
Sorry, I forgot to publish the latest version of this module to the terraform module registry. You can try the version `2.0.7`. Thank you.

**Comment by gboie** [comment]
Thank you! Solved in 2.0.7
