### ISSUE TITLE
Worker nodes do not have access to the cluster.

### ISSUE THREAD

**Issue by koshuang** [Young-ook/terraform-aws-spinnaker#130]
Hi there,

I was trying to create a spinnaker-managed-eks by following the [example](https://github.com/Young-ook/terraform-aws-spinnaker/tree/main/examples/spinnaker-managed-eks).

However in the `Node Group` Panel, it shows `Access Denied` with description `Your worker nodes do not have access to the cluster`.

![Screenshot from 2021-01-19 12-03-34](https://user-images.githubusercontent.com/1978357/104986881-28e5d800-5a4f-11eb-90b7-95c9e56d6371.png)

Do you have any suggestion to fix this issue? thanks!

**Comment by Young-ook** [comment]
Hi, 

This document could help you solve the problem: https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html#troubleshoot-managed-node-groups 
Thanks!
