### ISSUE TITLE
Issue running spinnaker example 

### ISSUE THREAD

**Issue by hlmcdougall** [Young-ook/terraform-aws-spinnaker#176]
When attempting to run terraform apply in the spinnaker example folder I get the following errors / warnings: 

│ Warning: Provider aws is undefined
│
│   on main.tf line 36, in module "spinnaker-managed-role":
│   36:   providers        = { aws = aws.prod }
│
│ Module module.spinnaker-managed-role does not declare a provider named aws.
│ If you wish to specify a provider configuration for the module, add an entry for aws in the required_providers
│ block within the module.
╵
╷
│ Error: no matching VPC found
│
│   with module.spinnaker.module.eks.data.aws_vpc.default,
│   on .terraform/modules/spinnaker.eks/network.tf line 4, in data "aws_vpc" "default":
│    4: data "aws_vpc" "default"

**Comment by Young-ook** [comment]
Hi, @hlmcdougall 
This module uses eks module inside that requires default vpc on your aws account.
This is the related issue (https://github.com/Young-ook/terraform-aws-eks/issues/44). For more details, please refer the repo (https://github.com/Young-ook/terraform-aws-eks). Thanks
